services:
  postgres:
    image: postgres:16.6
    container_name: django-postgres
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL = ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD = ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  # python-django:
  #   image: python:3.12.8-alpine
  #   container_name: python-django
  #   ports:
  #     - "8000:8000"
  # node:
  #   image: node:22.13-alpine
  #   container_name: node-react
  #   ports:
  #     - "3000:3000"
volumes:
  postgres-data:
  pgadmin-data: