services:
  postgres:
    image: postgres:16.6
    container_name: django-postgres
    env_file: postgres.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-postgres
    env_file: pgadmin.env.dev
    depends_on:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadm
  python-django:
    image: flixed-django:1.0
    container_name: python-django
    env_file: django.env.docker
    depends_on:
      - postgres
    volumes:
      - ./static:/django_app/staticfiles
  frontend-proxy:
    image: nginx:latest
    container_name: django-frontend-proxy
    ports:
      - "8001:80"
    depends_on:
      - python-django
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
  # node-react:
  #   image: flixed-react:1.0
  #   container_name: flixed-reactjs
  #   env_file: /Users/nilesh/Work/flixed-movie-tracker/flixed_reactjs/.env.development
  #   ports:
  #     - "8002:80"

volumes:
  postgres-data:
  pgadmin-data: