# Generated by Django 4.2.3 on 2023-12-22 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genre', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WatchList',
                'verbose_name_plural': 'WatchList',
            },
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genre', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('watched_date', models.DateField(auto_now_add=True)),
                ('times_watched', models.IntegerField(default=1)),
                ('language', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watched Movie',
                'verbose_name_plural': 'Watched Movies',
            },
        ),
    ]
