# Generated by Django 3.1.6 on 2021-02-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixedREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedmovies',
            name='times_watched',
            field=models.IntegerField(default=1),
        ),
    ]
