# Generated by Django 4.2.3 on 2024-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixedREST', '0002_updated_year_to_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='backDropUrl',
            field=models.CharField(default=None, max_length=100, blank=True, null=True),
            preserve_default=False,
        ),
    ]
