# Generated by Django 3.1.6 on 2021-05-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixedREST', '0003_added_language_to_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchListMovies',
            new_name='WatchList',
        ),
    ]
