# Generated by Django 4.2.3 on 2024-01-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixedREST', '0003_added_backdropUrl'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovie',
            name='backDropUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='backDropUrl',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
