# Generated by Django 4.2.3 on 2024-12-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixedREST', '0004_added_backdropUrl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedmovie',
            options={'ordering': ['watched_date'], 'verbose_name': 'Watched Movie', 'verbose_name_plural': 'Watched Movies'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['rating'], 'verbose_name': 'WatchList', 'verbose_name_plural': 'WatchList'},
        ),
    ]
