# Generated by Django 3.1.6 on 2021-05-29 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixedREST', '0006_added_user_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedmovie',
            name='watched_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 29, 9, 41, 52, 848571)),
        ),
    ]
