# Generated by Django 3.1.6 on 2021-09-12 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flixedREST', '0010_new_db_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genre', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('watched_date', models.DateField(default=datetime.date.today)),
                ('times_watched', models.IntegerField(default=1)),
                ('language', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watched Movie',
                'verbose_name_plural': 'Watched Movies',
            },
        ),
        migrations.CreateModel(
            name='Watch_List',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genre', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch List',
                'verbose_name_plural': 'Watch List',
            },
        ),
    ]
